using Auction.DAL.Entities;
using System.Data.Entity;

namespace Auction.DAL.EF
{
    public class StoreDbInitializer : DropCreateDatabaseIfModelChanges<AuctionContext>
    {
        protected override void Seed(AuctionContext db)
        {
            db.Categories.Add(new Category { Name = "Авто Мото" });
            db.Categories.Add(new Category { Name = "Телефоны Смартфоны" });
            db.Categories.Add(new Category { Name = "Ноутбуки ПК и планшеты" });
            db.Categories.Add(new Category { Name = "Техника и электроника" });
            db.Categories.Add(new Category { Name = "Спорт здоровье" });
            db.Categories.Add(new Category { Name = "Одежда мода красота" });
            db.Categories.Add(new Category { Name = "Детский мир" });
            db.Categories.Add(new Category { Name = "Дом досуг" });
            db.Categories.Add(new Category { Name = "Бакалея" });
            db.Categories.Add(new Category { Name = "Колекции антиквариат" });

            db.Categories.Add(new Category { Name = "Автозапчасти", ParentId = 1 });
            db.Categories.Add(new Category { Name = "Мототовары", ParentId = 1 });
            db.Categories.Add(new Category { Name = "Оборудование для СТО", ParentId = 1 });
            db.Categories.Add(new Category { Name = "Другие категории", ParentId = 1 });
            db.Categories.Add(new Category { Name = "Автоаксессуары", ParentId = 1 });
            db.Categories.Add(new Category { Name = "Электрика, автоприборы", ParentId = 1 });
            db.Categories.Add(new Category { Name = "Светотехника", ParentId = 1 });
            db.Categories.Add(new Category { Name = "Аудио-Видио, автозвук", ParentId = 1 });
            db.Categories.Add(new Category { Name = "Автомагнитолы", ParentId = 1 });
            db.Categories.Add(new Category { Name = "Тюнинг", ParentId = 1 });
            db.Categories.Add(new Category { Name = "Диски, колпаки", ParentId = 1 });
            db.Categories.Add(new Category { Name = "GPS устройства", ParentId = 1 });
            db.Categories.Add(new Category { Name = "Видеорегистраторы", ParentId = 1 });
            db.Categories.Add(new Category { Name = "Шины", ParentId = 1 });
            db.Categories.Add(new Category { Name = "Транспортные средства", ParentId = 1 });

            db.Categories.Add(new Category { Name = "Аксессуары и комплектующие", ParentId = 2 });
            db.Categories.Add(new Category { Name = "Стартовые пакеты, контракты", ParentId = 2 });
            db.Categories.Add(new Category { Name = "Телефоны, смартфоны", ParentId = 2 });

            db.Categories.Add(new Category { Name = "Комплектующие для ноутбуков", ParentId = 3 });
            db.Categories.Add(new Category { Name = "Аксессуары для планшетов", ParentId = 3 });
            db.Categories.Add(new Category { Name = "Принтеры, МФУ, Оргтехника", ParentId = 3 });
            db.Categories.Add(new Category { Name = "Комплектующие для ПК", ParentId = 3 });
            db.Categories.Add(new Category { Name = "Другая периферия", ParentId = 3 });
            db.Categories.Add(new Category { Name = "Мыши, клавиатуры, манипуляторы", ParentId = 3 });
            db.Categories.Add(new Category { Name = "Сетевое оборудование", ParentId = 3 });
            db.Categories.Add(new Category { Name = "Флешки, внешние HDD, диски", ParentId = 3 });
            db.Categories.Add(new Category { Name = "Ноутбуки", ParentId = 3 });
            db.Categories.Add(new Category { Name = "Мониторы", ParentId = 3 });
            db.Categories.Add(new Category { Name = "PSP, PlayStation, Xbox", ParentId = 3 });
            db.Categories.Add(new Category { Name = "Планшеты", ParentId = 3 });
            db.Categories.Add(new Category { Name = "Системные блоки, ПК", ParentId = 3 });
            db.Categories.Add(new Category { Name = "Электронные книги, помощники, КПК", ParentId = 3 });
            db.Categories.Add(new Category { Name = "Программное обеспечение", ParentId = 3 });
            db.Categories.Add(new Category { Name = "Сайты, домены, хостинг", ParentId = 3 });

            db.Categories.Add(new Category { Name = "Техника для кухни", ParentId = 4 });
            db.Categories.Add(new Category { Name = "Приборы гигиены", ParentId = 4 });
            db.Categories.Add(new Category { Name = "Техника для дома", ParentId = 4 });
            db.Categories.Add(new Category { Name = "Крупная бытовая техника", ParentId = 4 });
            db.Categories.Add(new Category { Name = "Климатическая техника", ParentId = 4 });
            
            db.Categories.Add(new Category { Name = "Всё для отдыха, туризм", ParentId = 5 });
            db.Categories.Add(new Category { Name = "Велосипеды и аксессуары к ним", ParentId = 5 });
            db.Categories.Add(new Category { Name = "Рыболовство", ParentId = 5 });
            db.Categories.Add(new Category { Name = "Спортинвентарь", ParentId = 5 });
            db.Categories.Add(new Category { Name = "Здоровье", ParentId = 5 });
            db.Categories.Add(new Category { Name = "Спортивное питание", ParentId = 5 });
            db.Categories.Add(new Category { Name = "Приборы и устройства", ParentId = 5 });
            db.Categories.Add(new Category { Name = "Спортивная одежда", ParentId = 5 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 5 });
            db.Categories.Add(new Category { Name = "Охота", ParentId = 5 });
            db.Categories.Add(new Category { Name = "Тренажеры", ParentId = 5 });
            db.Categories.Add(new Category { Name = "Катера, яхты", ParentId = 5 });

            db.Categories.Add(new Category { Name = "Женская одежда", ParentId = 6 });
            db.Categories.Add(new Category { Name = "Обувь", ParentId = 6 });
            db.Categories.Add(new Category { Name = "Мужская одежда", ParentId = 6 });
            db.Categories.Add(new Category { Name = "Галантерея и аксессуары", ParentId = 6 });
            db.Categories.Add(new Category { Name = "Сумки", ParentId = 6 });
            db.Categories.Add(new Category { Name = "Другие категории", ParentId = 6 });
            db.Categories.Add(new Category { Name = "Джинсы", ParentId = 6 });
            db.Categories.Add(new Category { Name = "Спортивные костюмы", ParentId = 6 });
            
            db.Categories.Add(new Category { Name = "Одежда", ParentId = 7 });
            db.Categories.Add(new Category { Name = "Игры, игрушки", ParentId = 7 });
            db.Categories.Add(new Category { Name = "Обувь", ParentId = 7 });
            db.Categories.Add(new Category { Name = "Детская литература", ParentId = 7 });
            db.Categories.Add(new Category { Name = "Аксессуары для детей", ParentId = 7 });
            db.Categories.Add(new Category { Name = "Канцелярские товары", ParentId = 7 });
            db.Categories.Add(new Category { Name = "Детская комната", ParentId = 7 });
            db.Categories.Add(new Category { Name = "Детский транспорт", ParentId = 7 });
            db.Categories.Add(new Category { Name = "Здоровье, гигиена", ParentId = 7 });
            db.Categories.Add(new Category { Name = "Другие категории", ParentId = 7 });
            db.Categories.Add(new Category { Name = "Коляски", ParentId = 7 });
            db.Categories.Add(new Category { Name = "Всё для молодых мам", ParentId = 7 });
            db.Categories.Add(new Category { Name = "Автокресла", ParentId = 7 });
            db.Categories.Add(new Category { Name = "Санки", ParentId = 7 });

            db.Categories.Add(new Category { Name = "Всё для кухни, посуда", ParentId = 8 });
            db.Categories.Add(new Category { Name = "Предметы интерьера", ParentId = 8 });
            db.Categories.Add(new Category { Name = "Освещение", ParentId = 8 });
            db.Categories.Add(new Category { Name = "Домашний текстиль", ParentId = 8 });
            db.Categories.Add(new Category { Name = "Всё для ванной комнаты", ParentId = 8 });
            db.Categories.Add(new Category { Name = "Системы безопастности", ParentId = 8 });
            db.Categories.Add(new Category { Name = "Мебель", ParentId = 8 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 8 });
            db.Categories.Add(new Category { Name = "Отопление", ParentId = 8 });
            db.Categories.Add(new Category { Name = "Сейфы", ParentId = 8 });
            
            db.Categories.Add(new Category { Name = "Кофе и какао", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Шоколад, печенье, конфеты, орехи, чипсы", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Чай", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Консервы, консервация", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Жевательные резинки и конфеты", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Растительные масла", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Специи", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Макаронные изделия", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Сыр", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Соусы", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Йогурты, закваски", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Мед", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Пищевые красители, ароматизаторы", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Напитки, соки, нектары", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Драже, леденцы", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Сахар, ваниль", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Смеси для выпечки", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Кондитерские наборы", ParentId = 9 });
            db.Categories.Add(new Category { Name = "Крупы", ParentId = 9 });

            db.Categories.Add(new Category { Name = "Книги", ParentId = 10 });
            db.Categories.Add(new Category { Name = "Филателия", ParentId = 10 });
            db.Categories.Add(new Category { Name = "Другие категории", ParentId = 10 });
            db.Categories.Add(new Category { Name = "Нумизматика (монеты)", ParentId = 10 });
            db.Categories.Add(new Category { Name = "Медали, ордена, значки, жетоны", ParentId = 10 });
            db.Categories.Add(new Category { Name = "Пластинки", ParentId = 10 });
            db.Categories.Add(new Category { Name = "Масштабные модели", ParentId = 10 });
            db.Categories.Add(new Category { Name = "Бонистика (банкноты и боны)", ParentId = 10 });
            db.Categories.Add(new Category { Name = "Столовое серебро, антикварная кухонная утварь", ParentId = 10 });
            db.Categories.Add(new Category { Name = "Картины, антикварная мебель", ParentId = 10 });
            db.Categories.Add(new Category { Name = "Скульптуры", ParentId = 10 });
            db.Categories.Add(new Category { Name = "Милитария", ParentId = 10 });
            db.Categories.Add(new Category { Name = "Иконы, складни, металлопластика", ParentId = 10 });
            db.Categories.Add(new Category { Name = "Монеты Украины из драг. сплавов", ParentId = 10 });
            db.Categories.Add(new Category { Name = "Коллекционное оружие", ParentId = 10 });

            db.Categories.Add(new Category { Name = "Другое", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Подвеска, амортизация", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Кузов", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Выхлопная система", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Электрика", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Двигатель", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Тормозная система", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Система охлаждения", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Система зажигания", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Система сцепления", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Ременной привод", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Масла", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Фильтры", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Система подачи топлива", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Карданный вал", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Отопление и вентиляция", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Коробка передач", ParentId = 11 });
            db.Categories.Add(new Category { Name = "Стеклоочистители", ParentId = 11 });
            db.Categories.Add(new Category { Name = "ГБО", ParentId = 11 });

            db.Categories.Add(new Category { Name = "Другое", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Экипировка", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Аксессуары", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Колесо", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Электрооборудование", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Силовой агрегат", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Трансмиссия", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Система питания", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Обвес, пластик", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Подвеска", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Тормозная система", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Система управления", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Рама", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Фильтра", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Выхлопная система", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Масла, технические жидкости", ParentId = 12 });
            db.Categories.Add(new Category { Name = "Система охлаждения", ParentId = 12 });

            db.Categories.Add(new Category { Name = "Гидро- и пневмооборудование, домкраты", ParentId = 13 });
            db.Categories.Add(new Category { Name = "Автомобильный специнструмент", ParentId = 13 });
            db.Categories.Add(new Category { Name = "Оборудование для диагностики", ParentId = 13 });
            db.Categories.Add(new Category { Name = "Ручной слесарный инструмент", ParentId = 13 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 13 });
            db.Categories.Add(new Category { Name = "Инструмент для рихтовки и покраски", ParentId = 13 });
            db.Categories.Add(new Category { Name = "Тросы, лебедки", ParentId = 13 });
            db.Categories.Add(new Category { Name = "Оборудование для шиномонтажа", ParentId = 13 });

            db.Categories.Add(new Category { Name = "Другое", ParentId = 14 });
            db.Categories.Add(new Category { Name = "Услуги", ParentId = 14 });

            db.Categories.Add(new Category { Name = "Другое", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Наклейки, эмблемы, значки", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Держатели мобильных, накладки", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Брелки, алкотестеры", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Средства аварийной помощи", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Автохимия, средства ухода за автомобилем", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Коврики", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Чехлы", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Мойки", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Подлокотники", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Очки", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Ароматизаторы", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Пылесосы", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Фаркопы", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Брызговики", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Ветровики", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Багажники", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Рамка для номера", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Автохолодильники", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Антибликовые козырьки", ParentId = 15 });
            db.Categories.Add(new Category { Name = "Обогреватели салона", ParentId = 15 });

            db.Categories.Add(new Category { Name = "Другое", ParentId = 16 });
            db.Categories.Add(new Category { Name = "Сигнализация", ParentId = 16 });
            db.Categories.Add(new Category { Name = "Автомобильные зарядки", ParentId = 16 });
            db.Categories.Add(new Category { Name = "Компрессоры", ParentId = 16 });
            db.Categories.Add(new Category { Name = "Инверторы", ParentId = 16 });
            db.Categories.Add(new Category { Name = "Датчики", ParentId = 16 });
            db.Categories.Add(new Category { Name = "Бортовые компьютеры", ParentId = 16 });
            db.Categories.Add(new Category { Name = "Прикуриватели", ParentId = 16 });
            db.Categories.Add(new Category { Name = "Парковочные радары", ParentId = 16 });
            db.Categories.Add(new Category { Name = "Разветвители", ParentId = 16 });
            db.Categories.Add(new Category { Name = "Радары", ParentId = 16 });

            db.Categories.Add(new Category { Name = "Лампы", ParentId = 17 });
            db.Categories.Add(new Category { Name = "Передняя оптика", ParentId = 17 });
            db.Categories.Add(new Category { Name = "Задняя оптика", ParentId = 17 });
            db.Categories.Add(new Category { Name = "Дополнительная оптика", ParentId = 17 });

            db.Categories.Add(new Category { Name = "Акустика (динамики)", ParentId = 18 });
            db.Categories.Add(new Category { Name = "Камеры заднего вида", ParentId = 18 });
            db.Categories.Add(new Category { Name = "FM-Модуляторы", ParentId = 18 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 18 });
            db.Categories.Add(new Category { Name = "Антенны", ParentId = 18 });
            db.Categories.Add(new Category { Name = "Кабели", ParentId = 18 });
            db.Categories.Add(new Category { Name = "Усилители", ParentId = 18 });
            db.Categories.Add(new Category { Name = "Мониторы (экраны)", ParentId = 18 });
            db.Categories.Add(new Category { Name = "Сабвуферы", ParentId = 18 });
            db.Categories.Add(new Category { Name = "Переходные рамки для автомагнитол", ParentId = 18 });

            db.Categories.Add(new Category { Name = "Внешний", ParentId = 20 });
            db.Categories.Add(new Category { Name = "Внутренний", ParentId = 20 });
            db.Categories.Add(new Category { Name = "Подсветка", ParentId = 20 });
            db.Categories.Add(new Category { Name = "Двигатель", ParentId = 20 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 20 });

            db.Categories.Add(new Category { Name = "Колпаки", ParentId = 21 });
            db.Categories.Add(new Category { Name = "Комплектующие", ParentId = 21 });
            db.Categories.Add(new Category { Name = "Стальные", ParentId = 21 });
            db.Categories.Add(new Category { Name = "Легкосплавные", ParentId = 21 });
            db.Categories.Add(new Category { Name = "Кованые", ParentId = 21 });

            db.Categories.Add(new Category { Name = "Аксессуары", ParentId = 22 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 22 });
            db.Categories.Add(new Category { Name = "GPS навигаторы", ParentId = 22 });

            db.Categories.Add(new Category { Name = "Зимние", ParentId = 24 });
            db.Categories.Add(new Category { Name = "Летние", ParentId = 24 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 24 });
            db.Categories.Add(new Category { Name = "Всесезонные", ParentId = 24 });
            db.Categories.Add(new Category { Name = "Грузовые", ParentId = 24 });
            db.Categories.Add(new Category { Name = "Шипованные", ParentId = 24 });

            db.Categories.Add(new Category { Name = "Другое", ParentId = 25 });
            db.Categories.Add(new Category { Name = "Мопеды, мотороллеры", ParentId = 25 });
            db.Categories.Add(new Category { Name = "Мотоциклы", ParentId = 25 });
            db.Categories.Add(new Category { Name = "Легковые авто", ParentId = 25 });
            db.Categories.Add(new Category { Name = "Грузовые, микроавтобусы", ParentId = 25 });

            db.Categories.Add(new Category { Name = "Чехлы, бампера", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Сенсорные экраны и Дисплеи", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Пленки для экранов", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Аккумуляторы", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Корпуса", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Шлейфы, переходники", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Разъемы, гнезда", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Кабели", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Зарядные устройства", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Динамики, микрофоны", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Внешние аккумуляторы (Power Bank)", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Проводные гарнитуры, наушники", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Модули камер", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Клавиатуры, клавиатурные модули", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Карты памяти", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Системные и дисплейные платы", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Микросхемы", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Умные часы (Smart watch)", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Bluetooth гарнитуры", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Антенны, усилители", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Инструкции, драйвера", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Колонки (портативные)", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Моноподы для селфи", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Док-станции, подставки", ParentId = 26 });
            db.Categories.Add(new Category { Name = "Стилусы", ParentId = 26 });

            db.Categories.Add(new Category { Name = "Киевстар, Djuice", ParentId = 27 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 27 });
            db.Categories.Add(new Category { Name = "МТС", ParentId = 27 });
            db.Categories.Add(new Category { Name = "Life", ParentId = 27 });
            db.Categories.Add(new Category { Name = "Beeline", ParentId = 27 });
            db.Categories.Add(new Category { Name = "Utel", ParentId = 27 });

            db.Categories.Add(new Category { Name = "Другие модели", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Samsung", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Nokia, Microsoft", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Apple iPhone", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Sony, Sony Ericsson", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Motorola", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Lenovo", ParentId = 28 });
            db.Categories.Add(new Category { Name = "LG", ParentId = 28 });
            db.Categories.Add(new Category { Name = "HTC", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Fly", ParentId = 28 });
            db.Categories.Add(new Category { Name = "BenQ-Siemens", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Prestigio", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Huawei", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Xiaomi", ParentId = 28 });
            db.Categories.Add(new Category { Name = "BlackBerry", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Alcatel", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Meizu", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Doogee", ParentId = 28 });
            db.Categories.Add(new Category { Name = "ZTE", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Asus", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Philips", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Cubot", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Jiayu", ParentId = 28 });
            db.Categories.Add(new Category { Name = "ThL", ParentId = 28 });
            db.Categories.Add(new Category { Name = "Pantech", ParentId = 28 });

            db.Categories.Add(new Category { Name = "Клавиатуры", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Аккумуляторы", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Корпуса", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Системы охлаждения", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Шлейфы", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Матрицы", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Адаптеры питания", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Микросхемы", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Аксессуары", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Жесткие диски", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Материнские платы", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Оперативная память", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Wi-Fi адаптеры", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Процессоры", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Приводы", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Звуковые карты", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Инверторы матриц", ParentId = 29 });
            db.Categories.Add(new Category { Name = "Видеокарты", ParentId = 29 });
            db.Categories.Add(new Category { Name = "PCMCIA карты", ParentId = 29 });

            db.Categories.Add(new Category { Name = "Комплектующие", ParentId = 30 });
            db.Categories.Add(new Category { Name = "Чехлы, сумки", ParentId = 30 });
            db.Categories.Add(new Category { Name = "Зарядные устройства, кабели", ParentId = 30 });
            db.Categories.Add(new Category { Name = "Защитные пленки, наклейки", ParentId = 30 });
            db.Categories.Add(new Category { Name = "Другие аксессуары", ParentId = 30 });
            db.Categories.Add(new Category { Name = "Клавиатуры, стилусы", ParentId = 30 });
            db.Categories.Add(new Category { Name = "Док-станции, переходники", ParentId = 30 });

            db.Categories.Add(new Category { Name = "Расходные материалы", ParentId = 31 });
            db.Categories.Add(new Category { Name = "Комплектующие", ParentId = 31 });
            db.Categories.Add(new Category { Name = "Принтеры", ParentId = 31 });
            db.Categories.Add(new Category { Name = "МФУ", ParentId = 31 });
            db.Categories.Add(new Category { Name = "Другая оргтехника", ParentId = 31 });
            db.Categories.Add(new Category { Name = "Факсы", ParentId = 31 });
            db.Categories.Add(new Category { Name = "Копировальные аппараты", ParentId = 31 });
            db.Categories.Add(new Category { Name = "Сканеры", ParentId = 31 });
            db.Categories.Add(new Category { Name = "3D-принтеры", ParentId = 31 });
            db.Categories.Add(new Category { Name = "Шредеры", ParentId = 31 });
            db.Categories.Add(new Category { Name = "аминаторы", ParentId = 31 });

            db.Categories.Add(new Category { Name = "Оперативная память", ParentId = 32 });
            db.Categories.Add(new Category { Name = "Материнские платы", ParentId = 32 });
            db.Categories.Add(new Category { Name = "Блоки питания", ParentId = 32 });
            db.Categories.Add(new Category { Name = "Жесткие диски", ParentId = 32 });
            db.Categories.Add(new Category { Name = "Корпуса", ParentId = 32 });
            db.Categories.Add(new Category { Name = "Видеокарты", ParentId = 32 });
            db.Categories.Add(new Category { Name = "Процессоры", ParentId = 32 });
            db.Categories.Add(new Category { Name = "Системы охлаждения", ParentId = 32 });
            db.Categories.Add(new Category { Name = "Шлейфы, переходники", ParentId = 32 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 32 });
            db.Categories.Add(new Category { Name = "Приводы", ParentId = 32 });
            db.Categories.Add(new Category { Name = "Звуковые карты", ParentId = 32 });
            db.Categories.Add(new Category { Name = "Модемные, сетевые карты", ParentId = 32 });
            db.Categories.Add(new Category { Name = "Комплекты для апгрейда", ParentId = 32 });
            db.Categories.Add(new Category { Name = "ТВ-тюнеры", ParentId = 32 });

            db.Categories.Add(new Category { Name = "Колонки, акустика", ParentId = 33 });
            db.Categories.Add(new Category { Name = "Аксессуары", ParentId = 33 });
            db.Categories.Add(new Category { Name = "UPS, ИБП", ParentId = 33 });
            db.Categories.Add(new Category { Name = "Web-Камеры", ParentId = 33 });
            db.Categories.Add(new Category { Name = "Сетевые фильтры", ParentId = 33 });
            db.Categories.Add(new Category { Name = "Концентраторы, хабы", ParentId = 33 });
            db.Categories.Add(new Category { Name = "Кардридеры", ParentId = 33 });
            db.Categories.Add(new Category { Name = "USB гаджеты", ParentId = 33 });
            db.Categories.Add(new Category { Name = "USB адаптеры", ParentId = 33 });

            db.Categories.Add(new Category { Name = "Мыши", ParentId = 34 });
            db.Categories.Add(new Category { Name = "Клавиатуры", ParentId = 34 });
            db.Categories.Add(new Category { Name = "Коврики", ParentId = 34 });
            db.Categories.Add(new Category { Name = "Геймпады", ParentId = 34 });
            db.Categories.Add(new Category { Name = "Джойстики", ParentId = 34 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 34 });
            db.Categories.Add(new Category { Name = "Рули", ParentId = 34 });
            db.Categories.Add(new Category { Name = "Комплекты", ParentId = 34 });
            db.Categories.Add(new Category { Name = "Компьютерные пульты ДУ", ParentId = 34 });
            db.Categories.Add(new Category { Name = "Графические планшеты", ParentId = 34 });

            db.Categories.Add(new Category { Name = "Маршрутизаторы", ParentId = 35 });
            db.Categories.Add(new Category { Name = "Кабели", ParentId = 35 });
            db.Categories.Add(new Category { Name = "Коммутаторы, Свитчи", ParentId = 35 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 35 });
            db.Categories.Add(new Category { Name = "Адаптеры", ParentId = 35 });
            db.Categories.Add(new Category { Name = "Модемы", ParentId = 35 });
            db.Categories.Add(new Category { Name = "Патч корды", ParentId = 35 });
            db.Categories.Add(new Category { Name = "Антенны", ParentId = 35 });
            db.Categories.Add(new Category { Name = "Серверы", ParentId = 35 });
            db.Categories.Add(new Category { Name = "Шкафы", ParentId = 35 });
            db.Categories.Add(new Category { Name = "IP-телефония", ParentId = 35 });

            db.Categories.Add(new Category { Name = "USB флешнакопители", ParentId = 36 });
            db.Categories.Add(new Category { Name = "Внешние жесткие диски", ParentId = 36 });
            db.Categories.Add(new Category { Name = "Диски", ParentId = 36 });
            db.Categories.Add(new Category { Name = "Твердотельные SSD-накопители", ParentId = 36 });
            db.Categories.Add(new Category { Name = "Карманы для HDD", ParentId = 36 });
            db.Categories.Add(new Category { Name = "Боксы, сумки, конверты", ParentId = 36 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 36 });

            db.Categories.Add(new Category { Name = "Другие модели", ParentId = 37 });
            db.Categories.Add(new Category { Name = "HP", ParentId = 37 });
            db.Categories.Add(new Category { Name = "Dell", ParentId = 37 });
            db.Categories.Add(new Category { Name = "Lenovo, IBM", ParentId = 37 });
            db.Categories.Add(new Category { Name = "Acer", ParentId = 37 });
            db.Categories.Add(new Category { Name = "Asus", ParentId = 37 });
            db.Categories.Add(new Category { Name = "Toshiba", ParentId = 37 });
            db.Categories.Add(new Category { Name = "Fujitsu", ParentId = 37 });
            db.Categories.Add(new Category { Name = "Samsung", ParentId = 37 });
            db.Categories.Add(new Category { Name = "MSI", ParentId = 37 });
            db.Categories.Add(new Category { Name = "Apple MacBook", ParentId = 37 });
            db.Categories.Add(new Category { Name = "Sony", ParentId = 37 });
            db.Categories.Add(new Category { Name = "LG", ParentId = 37 });
            db.Categories.Add(new Category { Name = "Panasonic", ParentId = 37 });

            db.Categories.Add(new Category { Name = "Другие производители", ParentId = 38 });
            db.Categories.Add(new Category { Name = "Комплектующие", ParentId = 38 });
            db.Categories.Add(new Category { Name = "Samsung", ParentId = 38 });
            db.Categories.Add(new Category { Name = "LG", ParentId = 38 });
            db.Categories.Add(new Category { Name = "Philips", ParentId = 38 });
            db.Categories.Add(new Category { Name = "Asus", ParentId = 38 });
            db.Categories.Add(new Category { Name = "Acer", ParentId = 38 });
            db.Categories.Add(new Category { Name = "HP", ParentId = 38 });
            db.Categories.Add(new Category { Name = "Dell", ParentId = 38 });
            db.Categories.Add(new Category { Name = "Benq", ParentId = 38 });
            db.Categories.Add(new Category { Name = "ViewSonic", ParentId = 38 });
            db.Categories.Add(new Category { Name = "AOC", ParentId = 38 });
            db.Categories.Add(new Category { Name = "Nec", ParentId = 38 });
            db.Categories.Add(new Category { Name = "Fujitsu-Siemens", ParentId = 38 });
            db.Categories.Add(new Category { Name = "Apple", ParentId = 38 });

            db.Categories.Add(new Category { Name = "Видеоигры", ParentId = 39 });
            db.Categories.Add(new Category { Name = "Аксессуары и комплектующие", ParentId = 39 });
            db.Categories.Add(new Category { Name = "Sony", ParentId = 39 });
            db.Categories.Add(new Category { Name = "Xbox", ParentId = 39 });
            db.Categories.Add(new Category { Name = "Другие модели", ParentId = 39 });
            db.Categories.Add(new Category { Name = "Nintendo", ParentId = 39 });
            db.Categories.Add(new Category { Name = "Sega", ParentId = 39 });
            db.Categories.Add(new Category { Name = "Dendy", ParentId = 39 });

            db.Categories.Add(new Category { Name = "Другие модели", ParentId = 40 });
            db.Categories.Add(new Category { Name = "iPad", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Asus", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Samsung", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Lenovo", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Acer", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Prestigio", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Cube", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Impression", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Ainol", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Dell", ParentId = 40 });
            db.Categories.Add(new Category { Name = "HP", ParentId = 40 });
            db.Categories.Add(new Category { Name = "LG", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Pipo", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Onda", ParentId = 40 });
            db.Categories.Add(new Category { Name = "FreeLander", ParentId = 40 });
            db.Categories.Add(new Category { Name = "HTC", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Sanei", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Archos", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Flytouch", ParentId = 40 });
            db.Categories.Add(new Category { Name = "Zenithink", ParentId = 40 });

            db.Categories.Add(new Category { Name = "Аксессуары", ParentId = 42 });
            db.Categories.Add(new Category { Name = "Калькуляторы", ParentId = 42 });
            db.Categories.Add(new Category { Name = "Электронные книги", ParentId = 42 });
            db.Categories.Add(new Category { Name = "КПК", ParentId = 42 });
            db.Categories.Add(new Category { Name = "Электронные записные книжки", ParentId = 42 });
            db.Categories.Add(new Category { Name = "Электронные словари, переводчики", ParentId = 42 });

            db.Categories.Add(new Category { Name = "Игры и развлечения", ParentId = 43 });
            db.Categories.Add(new Category { Name = "Операционные системы", ParentId = 43 });
            db.Categories.Add(new Category { Name = "Антивирусы, безопасность", ParentId = 43 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 43 });
            db.Categories.Add(new Category { Name = "Образование и наука", ParentId = 43 });
            db.Categories.Add(new Category { Name = "Офисные программы", ParentId = 43 });
            db.Categories.Add(new Category { Name = "Программы для смартфонов", ParentId = 43 });
            db.Categories.Add(new Category { Name = "Системные программы", ParentId = 43 });
            db.Categories.Add(new Category { Name = "Редакторы", ParentId = 43 });
            db.Categories.Add(new Category { Name = "Управление бизнесом, CRM и ERP", ParentId = 43 });
            db.Categories.Add(new Category { Name = "Электронные книги", ParentId = 43 });
            db.Categories.Add(new Category { Name = "Программы для Mac OS", ParentId = 43 });
            db.Categories.Add(new Category { Name = "Сеть и интернет", ParentId = 43 });
            db.Categories.Add(new Category { Name = "Бухгалтерия, склад, кадры", ParentId = 43 });
            db.Categories.Add(new Category { Name = "Хобби и увлечения", ParentId = 43 });

            db.Categories.Add(new Category { Name = "Чайники", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Аксессуары и комплектующие", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Блендеры", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Кофеварки, кофемашины, кофемолки", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Другая техника", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Кухонные весы", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Микроволновые печи", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Мультиварки", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Миксеры", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Фильтры для воды", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Мясорубки", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Соковыжималки", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Тостеры", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Кухонные комбайны", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Вафельницы", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Аэрогриль", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Пароварки", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Хлебопечки", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Сушилки", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Фритюрницы", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Йогуртницы, мороженицы", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Консервные, электроножи и ключи", ParentId = 45 });
            db.Categories.Add(new Category { Name = "Помпы для воды", ParentId = 45 });

            db.Categories.Add(new Category { Name = "Плойки", ParentId = 46 });
            db.Categories.Add(new Category { Name = "Фены", ParentId = 46 });
            db.Categories.Add(new Category { Name = "Машинки для стрижки", ParentId = 46 });
            db.Categories.Add(new Category { Name = "Электробритвы", ParentId = 46 });
            db.Categories.Add(new Category { Name = "Другая техника", ParentId = 46 });
            db.Categories.Add(new Category { Name = "Триммеры", ParentId = 46 });
            db.Categories.Add(new Category { Name = "Аксессуары и комплектующие", ParentId = 46 });
            db.Categories.Add(new Category { Name = "Эпиляторы", ParentId = 46 });
            db.Categories.Add(new Category { Name = "Электробигуди", ParentId = 46 });

            db.Categories.Add(new Category { Name = "Аксессуары и комплектующие", ParentId = 47 });
            db.Categories.Add(new Category { Name = "Утюги", ParentId = 47 });
            db.Categories.Add(new Category { Name = "Пылесосы", ParentId = 47 });
            db.Categories.Add(new Category { Name = "Другая техника", ParentId = 47 });
            db.Categories.Add(new Category { Name = "Швейные, вязальные машины", ParentId = 47 });
            db.Categories.Add(new Category { Name = "Пароочистители, паровые швабры", ParentId = 47 });

            db.Categories.Add(new Category { Name = "Аксессуары и комплектующие", ParentId = 48 });
            db.Categories.Add(new Category { Name = "Вытяжки", ParentId = 48 });
            db.Categories.Add(new Category { Name = "Стиральные машины", ParentId = 48 });
            db.Categories.Add(new Category { Name = "Варочные поверхности", ParentId = 48 });
            db.Categories.Add(new Category { Name = "Газовые, электроплиты", ParentId = 48 });
            db.Categories.Add(new Category { Name = "Водонагреватели", ParentId = 48 });
            db.Categories.Add(new Category { Name = "Встраиваемые духовки", ParentId = 48 });
            db.Categories.Add(new Category { Name = "Холодильники", ParentId = 48 });
            db.Categories.Add(new Category { Name = "Посудомоечные машины", ParentId = 48 });
            db.Categories.Add(new Category { Name = "Морозильники", ParentId = 48 });
            db.Categories.Add(new Category { Name = "Другая техника", ParentId = 48 });

            db.Categories.Add(new Category { Name = "Отопление", ParentId = 49 });
            db.Categories.Add(new Category { Name = "Аксессуары и комплектующие", ParentId = 49 });
            db.Categories.Add(new Category { Name = "Кондиционеры", ParentId = 49 });
            db.Categories.Add(new Category { Name = "Другая техника", ParentId = 49 });
            db.Categories.Add(new Category { Name = "Вентиляторы", ParentId = 49 });
            db.Categories.Add(new Category { Name = "Воздухоочистители, увлажнители", ParentId = 49 });

            db.Categories.Add(new Category { Name = "Ножи, мультитулы", ParentId = 50 });
            db.Categories.Add(new Category { Name = "Фонари, фонарики", ParentId = 50 });
            db.Categories.Add(new Category { Name = "Походный инвентарь", ParentId = 50 });
            db.Categories.Add(new Category { Name = "Рюкзаки", ParentId = 50 });
            db.Categories.Add(new Category { Name = "Посуда, фляги, термосы", ParentId = 50 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 50 });
            db.Categories.Add(new Category { Name = "Мангалы, гриль, шампура", ParentId = 50 });
            db.Categories.Add(new Category { Name = "Бассейны", ParentId = 50 });
            db.Categories.Add(new Category { Name = "Кемпинговая мебель", ParentId = 50 });
            db.Categories.Add(new Category { Name = "Спальные мешки, гамаки", ParentId = 50 });
            db.Categories.Add(new Category { Name = "Металлоискатели", ParentId = 50 });
            db.Categories.Add(new Category { Name = "Палатки", ParentId = 50 });
            db.Categories.Add(new Category { Name = "Дорожные сумки", ParentId = 50 });

            db.Categories.Add(new Category { Name = "Комплектующие", ParentId = 51 });
            db.Categories.Add(new Category { Name = "Экипировка для велоспорта", ParentId = 51 });
            db.Categories.Add(new Category { Name = "Снаряжение, аксессуары", ParentId = 51 });
            db.Categories.Add(new Category { Name = "Велосипеды", ParentId = 51 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 51 });

            db.Categories.Add(new Category { Name = "Рыбацкий инвентарь", ParentId = 52 });
            db.Categories.Add(new Category { Name = "Удилища", ParentId = 52 });
            db.Categories.Add(new Category { Name = "Катушки", ParentId = 52 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 52 });
            db.Categories.Add(new Category { Name = "Лодки, катамараны", ParentId = 52 });
            db.Categories.Add(new Category { Name = "Подводная охота", ParentId = 52 });
            db.Categories.Add(new Category { Name = "Эхолоты, радары", ParentId = 52 });

            db.Categories.Add(new Category { Name = "Водный спорт", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Настольные игры", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Боевые искусства", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Зимний спорт", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Игры с мячом", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Ролики, скейты", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Фитнес, йога, аэробика, гимнастика", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Альпинизм, спелеология", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Гантели, гири, штанги", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Теннис, бадминтон", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Пейнтбол, страйкбол", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Дартс", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Арбалеты, луки, стрелы", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Бильярд", ParentId = 53 });
            db.Categories.Add(new Category { Name = "Спортивные уголки", ParentId = 53 });

            db.Categories.Add(new Category { Name = "Ароматерапия, свечи, лампы", ParentId = 54 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 54 });
            db.Categories.Add(new Category { Name = "Нетрадиционная медицина", ParentId = 54 });
            db.Categories.Add(new Category { Name = "Диета", ParentId = 54 });
            db.Categories.Add(new Category { Name = "Очки, линзы, аксессуары", ParentId = 54 });

            db.Categories.Add(new Category { Name = "Другое", ParentId = 55 });
            db.Categories.Add(new Category { Name = "Аминокислоты", ParentId = 55 });
            db.Categories.Add(new Category { Name = "Протеин", ParentId = 55 });
            db.Categories.Add(new Category { Name = "Аксессуары", ParentId = 55 });
            db.Categories.Add(new Category { Name = "Витамины", ParentId = 55 });
            db.Categories.Add(new Category { Name = "Креатин", ParentId = 55 });
            db.Categories.Add(new Category { Name = "Гейнеры", ParentId = 55 });
            db.Categories.Add(new Category { Name = "Энергетические батончики", ParentId = 55 });

            db.Categories.Add(new Category { Name = "Другое", ParentId = 56 });
            db.Categories.Add(new Category { Name = "Массажеры", ParentId = 56 });
            db.Categories.Add(new Category { Name = "Весы", ParentId = 56 });
            db.Categories.Add(new Category { Name = "Тонометры", ParentId = 56 });
            db.Categories.Add(new Category { Name = "Фитнес браслеты", ParentId = 56 });
            db.Categories.Add(new Category { Name = "Термометры, градусники", ParentId = 56 });
            db.Categories.Add(new Category { Name = "Пояса, миостимуляторы", ParentId = 56 });
            db.Categories.Add(new Category { Name = "Кардиоприборы, приборы для пульса", ParentId = 56 });
            db.Categories.Add(new Category { Name = "Слуховые аппараты", ParentId = 56 });
            db.Categories.Add(new Category { Name = "Глюкометры", ParentId = 56 });
            db.Categories.Add(new Category { Name = "Приборы магнитотерапии", ParentId = 56 });
            db.Categories.Add(new Category { Name = "Шагомеры", ParentId = 56 });
            db.Categories.Add(new Category { Name = "Фильтры", ParentId = 56 });
            
            db.Categories.Add(new Category { Name = "Верхняя одежда", ParentId = 57 });
            db.Categories.Add(new Category { Name = "Обувь", ParentId = 57 });
            db.Categories.Add(new Category { Name = "Термобелье", ParentId = 57 });
            db.Categories.Add(new Category { Name = "Аксессуары", ParentId = 57 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 57 });

            db.Categories.Add(new Category { Name = "Другие", ParentId = 60 });
            db.Categories.Add(new Category { Name = "Силовые тренажёры", ParentId = 60 });
            db.Categories.Add(new Category { Name = "Скамьи и стойки", ParentId = 60 });
            db.Categories.Add(new Category { Name = "Велотренажёры", ParentId = 60 });
            db.Categories.Add(new Category { Name = "Орбитреки", ParentId = 60 });
            db.Categories.Add(new Category { Name = "Степперы", ParentId = 60 });
            db.Categories.Add(new Category { Name = "Беговые дорожки", ParentId = 60 });

            db.Categories.Add(new Category { Name = "Платья", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Блузки, рубашки", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Нижнее бельё", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Верхняя одежда", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Юбки", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Кофты", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Футболки", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Брюки", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Туники", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Купальники, парео", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Майки", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Свитера", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Пиджаки", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Сарафаны", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Шорты", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Топы", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Кардиганы", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Лосины, леггинсы", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Костюмы", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Жилеты", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Комбинезоны", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Бриджи", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Гольфы, водолазки", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Худи, толстовки", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Болеро", ParentId = 62 });
            db.Categories.Add(new Category { Name = "Капри", ParentId = 62 });

            db.Categories.Add(new Category { Name = "Женская обувь", ParentId = 63 });
            db.Categories.Add(new Category { Name = "Кроссовки", ParentId = 63 });
            db.Categories.Add(new Category { Name = "Мужская обувь", ParentId = 63 });
            db.Categories.Add(new Category { Name = "Кеды", ParentId = 63 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 63 });
            db.Categories.Add(new Category { Name = "Аксессуары", ParentId = 63 });
            db.Categories.Add(new Category { Name = "Средства по уходу", ParentId = 63 });

            db.Categories.Add(new Category { Name = "Верхняя одежда", ParentId = 64 });
            db.Categories.Add(new Category { Name = "Футболки, майки", ParentId = 64 });
            db.Categories.Add(new Category { Name = "Рубашки", ParentId = 64 });
            db.Categories.Add(new Category { Name = "Брюки", ParentId = 64 });
            db.Categories.Add(new Category { Name = "Свитера", ParentId = 64 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 64 });
            db.Categories.Add(new Category { Name = "Шорты", ParentId = 64 });
            db.Categories.Add(new Category { Name = "Костюмы, пиджаки, жилеты", ParentId = 64 });
            db.Categories.Add(new Category { Name = "Нижнее белье, плавки", ParentId = 64 });
            db.Categories.Add(new Category { Name = "Кофты", ParentId = 64 });
            db.Categories.Add(new Category { Name = "Толстовки", ParentId = 64 });

            db.Categories.Add(new Category { Name = "Очки", ParentId = 65 });
            db.Categories.Add(new Category { Name = "Портмоне, бумажники, кошельки", ParentId = 65 });
            db.Categories.Add(new Category { Name = "Ремни, пряжки", ParentId = 65 });
            db.Categories.Add(new Category { Name = "Зонты", ParentId = 65 });
            db.Categories.Add(new Category { Name = "Галстуки", ParentId = 65 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 65 });
            db.Categories.Add(new Category { Name = "Перчатки", ParentId = 65 });
            db.Categories.Add(new Category { Name = "Обложки для документов", ParentId = 65 });
            db.Categories.Add(new Category { Name = "Визитницы", ParentId = 65 });
            db.Categories.Add(new Category { Name = "Ключницы карманные", ParentId = 65 });
            db.Categories.Add(new Category { Name = "Барсетки", ParentId = 65 });
            db.Categories.Add(new Category { Name = "Зажимы для денег", ParentId = 65 });
            db.Categories.Add(new Category { Name = "Портфели", ParentId = 65 });
            db.Categories.Add(new Category { Name = "Варежки", ParentId = 65 });
            db.Categories.Add(new Category { Name = "Веера", ParentId = 65 });

            db.Categories.Add(new Category { Name = "Сумки", ParentId = 66 });
            db.Categories.Add(new Category { Name = "Рюкзаки", ParentId = 66 });
            db.Categories.Add(new Category { Name = "Клатчи", ParentId = 66 });
            db.Categories.Add(new Category { Name = "Дорожные сумки, чемоданы", ParentId = 66 });
            db.Categories.Add(new Category { Name = "Спортивные сумки", ParentId = 66 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 66 });

            db.Categories.Add(new Category { Name = "Головные уборы, шарфы", ParentId = 67 });
            db.Categories.Add(new Category { Name = "Чулочно-носочные изделия", ParentId = 67 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 67 });
            db.Categories.Add(new Category { Name = "Свадьба", ParentId = 67 });
            db.Categories.Add(new Category { Name = "Национальная одежда, обувь, аксессуары", ParentId = 67 });
            
            db.Categories.Add(new Category { Name = "Женские", ParentId = 68 });
            db.Categories.Add(new Category { Name = "Мужские", ParentId = 68 });

            db.Categories.Add(new Category { Name = "Универсальные", ParentId = 69 });
            db.Categories.Add(new Category { Name = "Для летних видов спорта", ParentId = 69 });
            db.Categories.Add(new Category { Name = "Для зимних видов спорта", ParentId = 69 });

            db.Categories.Add(new Category { Name = "Кофты, регланы", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Футболки, майки", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Верхняя одежда", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Платья, туники", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Головные уборы, шарфы", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Наборы, комплекты", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Боди, ползуны, распашонки", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Купальники, плавки", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Штаны", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Джинсы", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Шорты, бриджи, капри", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Блузки, рубашки", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Свитера, водолазки", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Пижамы, халаты", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Юбки", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Леггинсы, лосины", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Карнавальные костюмы", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Колготки, носки, гольфы", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Школьная форма", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Спортивные костюмы", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Нижнее белье", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Сарафаны", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Толстовки, худи", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Пиджаки", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Перчатки, варежки", ParentId = 70 });
            db.Categories.Add(new Category { Name = "Конверты, пеленки", ParentId = 70 });
            
            db.Categories.Add(new Category { Name = "Мягкие игрушки", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Куклы, пупсы, аксессуары", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Конструкторы", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Развивающие игрушки", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Машинки, железные дороги, треки", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Игры, настольные игры", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Радиоуправляемые игрушки", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Игровые центры, горки, качели, домики", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Сюжетно ролевые наборы", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Пазлы, мозаики", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Наборы для творчества", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Игрушечное оружие, рации", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Роботы, трансформеры", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Интерактивные игрушки", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Товары для водного отдыха", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Игровые фигурки", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Модели, сборные модели", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Погремушки, грызуны", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Квадрокоптеры", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Музыкальные инструменты", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Детский спортинвентарь", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Мобили, подвески, музыкальные карусели", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Игровые и развивающие коврики", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Спортивные стенки, батуты", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Игрушки для ванной", ParentId = 71 });
            db.Categories.Add(new Category { Name = "Корзины для игрушек", ParentId = 71 });
            
            db.Categories.Add(new Category { Name = "Кроссовки, кеды, мокасины, бутсы", ParentId = 72 });
            db.Categories.Add(new Category { Name = "Сапоги, ботинки", ParentId = 72 });
            db.Categories.Add(new Category { Name = "Сандалии, босоножки, шлепанцы", ParentId = 72 });
            db.Categories.Add(new Category { Name = "Туфли", ParentId = 72 });
            db.Categories.Add(new Category { Name = "Тапочки, чешки", ParentId = 72 });
            db.Categories.Add(new Category { Name = "Резиновые сапоги", ParentId = 72 });
            db.Categories.Add(new Category { Name = "Пинетки", ParentId = 72 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 72 });

            db.Categories.Add(new Category { Name = "Сказки", ParentId = 73 });
            db.Categories.Add(new Category { Name = "Повести, рассказы", ParentId = 73 });
            db.Categories.Add(new Category { Name = "Другая детская литература", ParentId = 73 });
            db.Categories.Add(new Category { Name = "Познавательная литература, энциклопедии", ParentId = 73 });
            db.Categories.Add(new Category { Name = "Приключения", ParentId = 73 });
            db.Categories.Add(new Category { Name = "Стихотворения", ParentId = 73 });
            db.Categories.Add(new Category { Name = "Школьная и учебная литература", ParentId = 73 });
            db.Categories.Add(new Category { Name = "Обучающая литература, азбуки, буквари", ParentId = 73 });
            db.Categories.Add(new Category { Name = "Фантастика", ParentId = 73 });
            db.Categories.Add(new Category { Name = "Книги для родителей", ParentId = 73 });
            db.Categories.Add(new Category { Name = "Книги по мультфильмам", ParentId = 73 });
            db.Categories.Add(new Category { Name = "Комиксы, раскраски", ParentId = 73 });
            db.Categories.Add(new Category { Name = "Детский детектив", ParentId = 73 });

            db.Categories.Add(new Category { Name = "Рюкзаки, сумки", ParentId = 74 });
            db.Categories.Add(new Category { Name = "Резинки, заколки, обручи", ParentId = 74 });
            db.Categories.Add(new Category { Name = "Очки и аксессуары", ParentId = 74 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 74 });
            db.Categories.Add(new Category { Name = "Ремни, пояса, подтяжки", ParentId = 74 });
            db.Categories.Add(new Category { Name = "Косметика и украшения для девочек", ParentId = 74 });
            db.Categories.Add(new Category { Name = "Зонты, дождевики", ParentId = 74 });
            db.Categories.Add(new Category { Name = "Галстуки, бабочки", ParentId = 74 });
            
            db.Categories.Add(new Category { Name = "Ручки, карандаши, фломастеры, маркеры", ParentId = 75 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 75 });
            db.Categories.Add(new Category { Name = "Тетради ученические, нотные, прописи", ParentId = 75 });
            db.Categories.Add(new Category { Name = "Пеналы, футляры, подставки для книг", ParentId = 75 });
            db.Categories.Add(new Category { Name = "Краски, кисти", ParentId = 75 });
            db.Categories.Add(new Category { Name = "Дневники, детские блокноты и записные книжки", ParentId = 75 });
            db.Categories.Add(new Category { Name = "Магниты и наклейки", ParentId = 75 });
            db.Categories.Add(new Category { Name = "Обложки для книг и тетрадей", ParentId = 75 });
            db.Categories.Add(new Category { Name = "Бумага и альбомы для рисования", ParentId = 75 });
            db.Categories.Add(new Category { Name = "Цветная бумага и картон", ParentId = 75 });
            db.Categories.Add(new Category { Name = "Глобусы, атласные и контурные карты", ParentId = 75 });
            
            db.Categories.Add(new Category { Name = "Постельные принадлежности", ParentId = 76 });
            db.Categories.Add(new Category { Name = "Стулья и подушки для кормления", ParentId = 76 });
            db.Categories.Add(new Category { Name = "Парты, столики, мольберты", ParentId = 76 });
            db.Categories.Add(new Category { Name = "Кроватки, люльки, колыбельки", ParentId = 76 });
            db.Categories.Add(new Category { Name = "Матрацы, одеяла, подушки", ParentId = 76 });
            db.Categories.Add(new Category { Name = "Освещение", ParentId = 76 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 76 });
            db.Categories.Add(new Category { Name = "Кресло-качалки, качели", ParentId = 76 });
            db.Categories.Add(new Category { Name = "Манежи", ParentId = 76 });
            db.Categories.Add(new Category { Name = "Комоды, пеленаторы", ParentId = 76 });
            db.Categories.Add(new Category { Name = "Видео-, радионяни", ParentId = 76 });

            db.Categories.Add(new Category { Name = "Каталки, качалки", ParentId = 77 });
            db.Categories.Add(new Category { Name = "Велосипеды", ParentId = 77 });
            db.Categories.Add(new Category { Name = "Детские ролики и скейты", ParentId = 77 });
            db.Categories.Add(new Category { Name = "Самокаты", ParentId = 77 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 77 });
            db.Categories.Add(new Category { Name = "Электромобили", ParentId = 77 });
            db.Categories.Add(new Category { Name = "Ходунки", ParentId = 77 });
            db.Categories.Add(new Category { Name = "Рюкзачки-кенгуру", ParentId = 77 });
            db.Categories.Add(new Category { Name = "Слинги", ParentId = 77 });

            db.Categories.Add(new Category { Name = "Все для кормления", ParentId = 78 });
            db.Categories.Add(new Category { Name = "Все для купания", ParentId = 78 });
            db.Categories.Add(new Category { Name = "Подгузники, салфетки", ParentId = 78 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 78 });
            db.Categories.Add(new Category { Name = "Горшки, накладки на унитаз", ParentId = 78 });
            db.Categories.Add(new Category { Name = "Градусники, термометры, весы", ParentId = 78 });
            db.Categories.Add(new Category { Name = "Крема, масла, присыпки", ParentId = 78 });
            
            db.Categories.Add(new Category { Name = "Другое", ParentId = 79 });
            db.Categories.Add(new Category { Name = "Видео и аудио для детей", ParentId = 79 });

            db.Categories.Add(new Category { Name = "Штаны, капри, бриджи", ParentId = 81 });
            db.Categories.Add(new Category { Name = "Футболки, туники, блузки", ParentId = 81 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 81 });
            db.Categories.Add(new Category { Name = "Нижнее белье", ParentId = 81 });
            db.Categories.Add(new Category { Name = "Платья", ParentId = 81 });
            db.Categories.Add(new Category { Name = "Сарафаны", ParentId = 81 });
            db.Categories.Add(new Category { Name = "Юбки", ParentId = 81 });
            db.Categories.Add(new Category { Name = "Верхняя одежда", ParentId = 81 });
            db.Categories.Add(new Category { Name = "Комбинезоны", ParentId = 81 });

            db.Categories.Add(new Category { Name = "Другое", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Тарелки, блюда", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Ножи, ножницы, точилки", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Сковородки", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Рюмки, бокалы, стаканы", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Кастрюли, наборы", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Салатницы, конфетницы, пиалы", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Чашки, кружки", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Кухонный инвентарь", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Формы для выпечки", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Пластиковая посуда", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Столовые приборы", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Сервизы", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Ёмкости для сыпучих продуктов", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Чайники", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Наборы для специй, сахарницы", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Термосы", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Салфетки, салфетницы, подставки", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Кувшины, графины, бутылки", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Кондитерские принадлежности", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Кухонные наборы", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Разделочные доски", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Терки, овощерезки", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Кофемолки, кофеварки, турки", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Моющие средства для кухни", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Заварники", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Дуршлаги, сита", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Миски", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Подносы", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Кухонные мойки", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Наборы для суши, палочки", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Подстаканники", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Мясорубки, лапшерезки", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Формы для льда", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Хлебницы", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Наборы для фондю, мармиты", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Пельменницы", ParentId = 84 });
            db.Categories.Add(new Category { Name = "Формы для варки яиц", ParentId = 84 });
            
            db.Categories.Add(new Category { Name = "Статуэтки, фигурки", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Подушки декоративные", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Шкатулки, копилки", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Картины", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Вазы", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Панно, подвески, колокольчики", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Подсвечники", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Свечи декоративные, гелевые", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Талисманы, обереги", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Маски, веера", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Декоративная посуда", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Декоративные коробки, органайзеры", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Вешалки, ключницы", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Интерьерные наклейки, стикеры", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Песочные часы", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Зеркала", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Термометры, барометры", ParentId = 85 });
            db.Categories.Add(new Category { Name = "Фотообои", ParentId = 85 });

            db.Categories.Add(new Category { Name = "Стабилизаторы, ИБП", ParentId = 86 });
            db.Categories.Add(new Category { Name = "Лампы, лампочки", ParentId = 86 });
            db.Categories.Add(new Category { Name = "Светодиодные ленты, блоки питания, контроллеры", ParentId = 86 });
            db.Categories.Add(new Category { Name = "Светильники", ParentId = 86 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 86 });
            db.Categories.Add(new Category { Name = "Прожекторы", ParentId = 86 });
            db.Categories.Add(new Category { Name = "Лампы настольные", ParentId = 86 });
            db.Categories.Add(new Category { Name = "Люстры, плафоны", ParentId = 86 });
            db.Categories.Add(new Category { Name = "Ночники", ParentId = 86 });
            db.Categories.Add(new Category { Name = "Датчики движения", ParentId = 86 });
            
            db.Categories.Add(new Category { Name = "Постельное белье", ParentId = 87 });
            db.Categories.Add(new Category { Name = "Полотенца", ParentId = 87 });
            db.Categories.Add(new Category { Name = "Покрывала", ParentId = 87 });
            db.Categories.Add(new Category { Name = "Подушки", ParentId = 87 });
            db.Categories.Add(new Category { Name = "Одеяла", ParentId = 87 });
            db.Categories.Add(new Category { Name = "Шторы, подхваты", ParentId = 87 });
            db.Categories.Add(new Category { Name = "Скатерти, фартуки", ParentId = 87 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 87 });
            db.Categories.Add(new Category { Name = "Ковры", ParentId = 87 });
            db.Categories.Add(new Category { Name = "Жалюзи, ролеты", ParentId = 87 });

            db.Categories.Add(new Category { Name = "Другое", ParentId = 88 });
            db.Categories.Add(new Category { Name = "Хозяйственные товары", ParentId = 88 });
            db.Categories.Add(new Category { Name = "Краны, смесители", ParentId = 88 });
            db.Categories.Add(new Category { Name = "Аксессуары для ванной комнаты", ParentId = 88 });
            db.Categories.Add(new Category { Name = "Ванны, душевые кабины", ParentId = 88 });
            db.Categories.Add(new Category { Name = "Умывальники", ParentId = 88 });
            db.Categories.Add(new Category { Name = "Полотенцесушители", ParentId = 88 });
            db.Categories.Add(new Category { Name = "Унитазы", ParentId = 88 });
            
            db.Categories.Add(new Category { Name = "Видеонаблюдение", ParentId = 89 });
            db.Categories.Add(new Category { Name = "Сигнализация", ParentId = 89 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 89 });
            db.Categories.Add(new Category { Name = "Домофоны", ParentId = 89 });

            db.Categories.Add(new Category { Name = "Мебельная фурнитура", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Кресла", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Детская мебель", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Столы", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Надувная мебель", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Стенки, горки", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Бескаркасная мебель", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Тумбы, комоды", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Прихожие", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Кухни", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Стулья", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Спальни", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Диваны", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Шкафы", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Матрасы", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Полки", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Кровати", ParentId = 90 });
            db.Categories.Add(new Category { Name = "Гладильные доски", ParentId = 90 });

            db.Categories.Add(new Category { Name = "Камины и сауны", ParentId = 92 });
            db.Categories.Add(new Category { Name = "Котлы", ParentId = 92 });
            db.Categories.Add(new Category { Name = "Комплектующие", ParentId = 92 });
            db.Categories.Add(new Category { Name = "Теплый пол", ParentId = 92 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 92 });
            db.Categories.Add(new Category { Name = "Радиаторы", ParentId = 92 });
            
            db.Categories.Add(new Category { Name = "Офисные", ParentId = 93 });
            db.Categories.Add(new Category { Name = "Мебельные и гостиничные", ParentId = 93 });
            db.Categories.Add(new Category { Name = "Оружейные", ParentId = 93 });
            db.Categories.Add(new Category { Name = "Встраиваемые", ParentId = 93 });
            db.Categories.Add(new Category { Name = "Бухгалтерские и архивные", ParentId = 93 });
            db.Categories.Add(new Category { Name = "Банковские", ParentId = 93 });

            db.Categories.Add(new Category { Name = "Современные издания книг", ParentId = 114 });
            db.Categories.Add(new Category { Name = "Антикварные издания книг", ParentId = 114 });

            db.Categories.Add(new Category { Name = "Тематические коллекции марок", ParentId = 115 });
            db.Categories.Add(new Category { Name = "Марки СССР, России и стран СНГ", ParentId = 115 });
            db.Categories.Add(new Category { Name = "Конверты, почтовые карточки", ParentId = 115 });
            db.Categories.Add(new Category { Name = "Марки Европы", ParentId = 115 });
            db.Categories.Add(new Category { Name = "Марки Украины", ParentId = 115 });
            db.Categories.Add(new Category { Name = "Марки Азии", ParentId = 115 });
            db.Categories.Add(new Category { Name = "Марки Германии", ParentId = 115 });
            db.Categories.Add(new Category { Name = "Марки Америки", ParentId = 115 });
            db.Categories.Add(new Category { Name = "Марки Африки", ParentId = 115 });
            db.Categories.Add(new Category { Name = "Марки Австралии и Океании", ParentId = 115 });
            db.Categories.Add(new Category { Name = "Каталоги, книги, аксессуары", ParentId = 115 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 115 });
            db.Categories.Add(new Category { Name = "Копии марок", ParentId = 115 });

            db.Categories.Add(new Category { Name = "Открытки, календари, афиши", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Игрушки", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Раритетные документы", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Карманные и наручные часы", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Ювелирные изделия, бижутерия", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Бирофилия", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Фан-сектор", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Минералы и окаменелости", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Вкладыши от жвачек", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Талоны и билеты", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Пластиковые карты", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Филумения", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Пакетики с сахаром", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Номерные знаки", ParentId = 116 });
            db.Categories.Add(new Category { Name = "Металлоискатели и аксессуары", ParentId = 116 });
            
            db.Categories.Add(new Category { Name = "Европа", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Россия и СССР", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Монеты Украины из недраг. сплавов", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Царская Россия до 1894", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Азия", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Германия", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Монеты США", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Монеты эпохи Николая II (1895 -1917)", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Польша", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Африка", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Великобритания", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Копии, подделки", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Литература, аксессуары", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Северная Америка", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Южная Америка", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Австралия и Океания", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Античные, Золотая Орда", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Страны Карибского бассейна", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Средневековая Европа", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Специальные выпуски, коллекции", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 117 });
            db.Categories.Add(new Category { Name = "Сувенирная продукция", ParentId = 117 });
            
            db.Categories.Add(new Category { Name = "Значки", ParentId = 118 });
            db.Categories.Add(new Category { Name = "Награды, медали, ордена", ParentId = 118 });
            db.Categories.Add(new Category { Name = "Знаки отличий", ParentId = 118 });
            db.Categories.Add(new Category { Name = "Жетоны", ParentId = 118 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 118 });
            db.Categories.Add(new Category { Name = "Копии медалей и знаков", ParentId = 118 });
            db.Categories.Add(new Category { Name = "Литература, СD / DVD", ParentId = 118 });

            db.Categories.Add(new Category { Name = "Авто / мото", ParentId = 120 });
            db.Categories.Add(new Category { Name = "Фигурки", ParentId = 120 });
            db.Categories.Add(new Category { Name = "Железнодорожные", ParentId = 120 });
            db.Categories.Add(new Category { Name = "Военная техника", ParentId = 120 });
            db.Categories.Add(new Category { Name = "Авиация", ParentId = 120 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 120 });
            db.Categories.Add(new Category { Name = "Флот", ParentId = 120 });
            db.Categories.Add(new Category { Name = "Каталоги", ParentId = 120 });

            db.Categories.Add(new Category { Name = "Россия, СССР", ParentId = 121 });
            db.Categories.Add(new Category { Name = "Украина", ParentId = 121 });
            db.Categories.Add(new Category { Name = "Европа", ParentId = 121 });
            db.Categories.Add(new Category { Name = "Азия", ParentId = 121 });
            db.Categories.Add(new Category { Name = "Копии", ParentId = 121 });
            db.Categories.Add(new Category { Name = "Африка", ParentId = 121 });
            db.Categories.Add(new Category { Name = "Акции, облигации, лотереи", ParentId = 121 });
            db.Categories.Add(new Category { Name = "Южная Америка", ParentId = 121 });
            db.Categories.Add(new Category { Name = "Северная Америка", ParentId = 121 });
            db.Categories.Add(new Category { Name = "Чеки", ParentId = 121 });
            db.Categories.Add(new Category { Name = "Каталоги, книги, аксессуары", ParentId = 121 });
            db.Categories.Add(new Category { Name = "Австралия и Океания", ParentId = 121 });
            db.Categories.Add(new Category { Name = "Центральная Америка", ParentId = 121 });
            db.Categories.Add(new Category { Name = "Карибский бассейн", ParentId = 121 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 121 });
            
            db.Categories.Add(new Category { Name = "Тарелки, блюда, блюдца", ParentId = 122 });
            db.Categories.Add(new Category { Name = "Вазы, горшки, сосуды, бутылки", ParentId = 122 });
            db.Categories.Add(new Category { Name = "Столовые приборы", ParentId = 122 });
            db.Categories.Add(new Category { Name = "Наборы, сервизы", ParentId = 122 });
            db.Categories.Add(new Category { Name = "Рюмки, стопки, бокалы", ParentId = 122 });
            db.Categories.Add(new Category { Name = "Самовары, чайники, заварники", ParentId = 122 });
            db.Categories.Add(new Category { Name = "Спецовники", ParentId = 122 });
            db.Categories.Add(new Category { Name = "Кружки, чашки", ParentId = 122 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 122 });
            db.Categories.Add(new Category { Name = "Графины, Штофы", ParentId = 122 });
            db.Categories.Add(new Category { Name = "Стаканы, подстаканники", ParentId = 122 });
            db.Categories.Add(new Category { Name = "Подносы", ParentId = 122 });
            db.Categories.Add(new Category { Name = "Подставки, салфетницы", ParentId = 122 });
            db.Categories.Add(new Category { Name = "Кофейники, турки", ParentId = 122 });
            
            db.Categories.Add(new Category { Name = "Картины", ParentId = 123 });
            db.Categories.Add(new Category { Name = "Техника и приборы", ParentId = 123 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 123 });
            db.Categories.Add(new Category { Name = "Для гостиной", ParentId = 123 });
            db.Categories.Add(new Category { Name = "Настольные и каминные часы", ParentId = 123 });
            db.Categories.Add(new Category { Name = "Подсвечники", ParentId = 123 });
            db.Categories.Add(new Category { Name = "Для кухни", ParentId = 123 });
            db.Categories.Add(new Category { Name = "Настенные часы", ParentId = 123 });
            db.Categories.Add(new Category { Name = "Для спальни", ParentId = 123 });

            db.Categories.Add(new Category { Name = "Фарфор", ParentId = 124 });
            db.Categories.Add(new Category { Name = "Другие", ParentId = 124 });
            db.Categories.Add(new Category { Name = "Бронза", ParentId = 124 });
            db.Categories.Add(new Category { Name = "Шпиатр", ParentId = 124 });
            db.Categories.Add(new Category { Name = "Дерево", ParentId = 124 });
            db.Categories.Add(new Category { Name = "Фаянс", ParentId = 124 });
            db.Categories.Add(new Category { Name = "Стекло", ParentId = 124 });
            db.Categories.Add(new Category { Name = "Чугун", ParentId = 124 });
            db.Categories.Add(new Category { Name = "Латунь", ParentId = 124 });

            db.Categories.Add(new Category { Name = "Амуниция", ParentId = 125 });
            db.Categories.Add(new Category { Name = "Нашивки и шевроны", ParentId = 125 });
            db.Categories.Add(new Category { Name = "Погоны и петлицы", ParentId = 125 });
            db.Categories.Add(new Category { Name = "Пуговицы", ParentId = 125 });
            db.Categories.Add(new Category { Name = "Литература", ParentId = 125 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 125 });
            db.Categories.Add(new Category { Name = "Предметы времен войны", ParentId = 125 });
            db.Categories.Add(new Category { Name = "Кокарды", ParentId = 125 });
            
            db.Categories.Add(new Category { Name = "Иконы", ParentId = 126 });
            db.Categories.Add(new Category { Name = "Другое", ParentId = 126 });
            db.Categories.Add(new Category { Name = "Кресты", ParentId = 126 });
            db.Categories.Add(new Category { Name = "Складни", ParentId = 126 });
            db.Categories.Add(new Category { Name = "Ладанки", ParentId = 126 });
            db.Categories.Add(new Category { Name = "Киоты", ParentId = 126 });
        }
    }
}
